/*
Etsy Open API v3

Testing ShopListingVariationImageApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ShopListingVariationImageApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShopListingVariationImageApiService GetListingVariationImages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shopId int32
		var listingId int32

		resp, httpRes, err := apiClient.ShopListingVariationImageApi.GetListingVariationImages(context.Background(), shopId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShopListingVariationImageApiService UpdateVariationImages", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shopId int32
		var listingId int32

		resp, httpRes, err := apiClient.ShopListingVariationImageApi.UpdateVariationImages(context.Background(), shopId, listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
