/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShopListingWithAssociationsImagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShopListingWithAssociationsImagesInner{}

// ShopListingWithAssociationsImagesInner Represents a list of listing image resources, each of which contains the reference URLs and metadata for an image
type ShopListingWithAssociationsImagesInner struct {
	// The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.
	ListingId *int32 `json:"listing_id,omitempty"`
	// The numeric ID of the primary [listing image](/documentation/reference#tag/ShopListing-Image) for this transaction.
	ListingImageId *int32 `json:"listing_image_id,omitempty"`
	// The webhex string for the image's average color, in webhex notation.
	HexCode NullableString `json:"hex_code,omitempty"`
	// The numeric red value equal to the image's average red value, from 0-255 (RGB color).
	Red NullableInt32 `json:"red,omitempty"`
	// The numeric red value equal to the image's average red value, from 0-255 (RGB color).
	Green NullableInt32 `json:"green,omitempty"`
	// The numeric red value equal to the image's average red value, from 0-255 (RGB color).
	Blue NullableInt32 `json:"blue,omitempty"`
	// The numeric hue equal to the image's average hue, from 0-360 (HSV color).
	Hue NullableInt32 `json:"hue,omitempty"`
	// The numeric saturation equal to the image's average saturation, from 0-100 (HSV color).
	Saturation NullableInt32 `json:"saturation,omitempty"`
	// The numeric brightness equal to the image's average brightness, from 0-100 (HSV color).
	Brightness NullableInt32 `json:"brightness,omitempty"`
	// When true, the image is in black & white.
	IsBlackAndWhite NullableBool `json:"is_black_and_white,omitempty"`
	// The listing image\\'s creation time, in epoch seconds.
	CreationTsz *int32 `json:"creation_tsz,omitempty"`
	// The listing image\\'s creation time, in epoch seconds.
	CreatedTimestamp *int32 `json:"created_timestamp,omitempty"`
	// The positive non-zero numeric position in the images displayed in a listing, with rank 1 images appearing in the left-most position in a listing.
	Rank *int32 `json:"rank,omitempty"`
	// The url string for a 75x75 pixel thumbnail of the image.
	Url75x75 *string `json:"url_75x75,omitempty"`
	// The url string for a 170x135 pixel thumbnail of the image.
	Url170x135 *string `json:"url_170x135,omitempty"`
	// The url string for a thumbnail of the image, no more than 570 pixels wide with variable height.
	Url570xN *string `json:"url_570xN,omitempty"`
	// The url string for the full-size image, up to 3000 pixels in each dimension.
	UrlFullxfull *string `json:"url_fullxfull,omitempty"`
	// The numeric height, measured in pixels, of the full-sized image referenced in url_fullxfull.
	FullHeight NullableInt32 `json:"full_height,omitempty"`
	// The numeric width, measured in pixels, of the full-sized image referenced in url_fullxfull.
	FullWidth NullableInt32 `json:"full_width,omitempty"`
	// Alt text for the listing image.
	AltText NullableString `json:"alt_text,omitempty"`
}

// NewShopListingWithAssociationsImagesInner instantiates a new ShopListingWithAssociationsImagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShopListingWithAssociationsImagesInner() *ShopListingWithAssociationsImagesInner {
	this := ShopListingWithAssociationsImagesInner{}
	return &this
}

// NewShopListingWithAssociationsImagesInnerWithDefaults instantiates a new ShopListingWithAssociationsImagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShopListingWithAssociationsImagesInnerWithDefaults() *ShopListingWithAssociationsImagesInner {
	this := ShopListingWithAssociationsImagesInner{}
	return &this
}

// GetListingId returns the ListingId field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetListingId() int32 {
	if o == nil || IsNil(o.ListingId) {
		var ret int32
		return ret
	}
	return *o.ListingId
}

// GetListingIdOk returns a tuple with the ListingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetListingIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ListingId) {
		return nil, false
	}
	return o.ListingId, true
}

// HasListingId returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasListingId() bool {
	if o != nil && !IsNil(o.ListingId) {
		return true
	}

	return false
}

// SetListingId gets a reference to the given int32 and assigns it to the ListingId field.
func (o *ShopListingWithAssociationsImagesInner) SetListingId(v int32) {
	o.ListingId = &v
}

// GetListingImageId returns the ListingImageId field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetListingImageId() int32 {
	if o == nil || IsNil(o.ListingImageId) {
		var ret int32
		return ret
	}
	return *o.ListingImageId
}

// GetListingImageIdOk returns a tuple with the ListingImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetListingImageIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ListingImageId) {
		return nil, false
	}
	return o.ListingImageId, true
}

// HasListingImageId returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasListingImageId() bool {
	if o != nil && !IsNil(o.ListingImageId) {
		return true
	}

	return false
}

// SetListingImageId gets a reference to the given int32 and assigns it to the ListingImageId field.
func (o *ShopListingWithAssociationsImagesInner) SetListingImageId(v int32) {
	o.ListingImageId = &v
}

// GetHexCode returns the HexCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetHexCode() string {
	if o == nil || IsNil(o.HexCode.Get()) {
		var ret string
		return ret
	}
	return *o.HexCode.Get()
}

// GetHexCodeOk returns a tuple with the HexCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetHexCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HexCode.Get(), o.HexCode.IsSet()
}

// HasHexCode returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasHexCode() bool {
	if o != nil && o.HexCode.IsSet() {
		return true
	}

	return false
}

// SetHexCode gets a reference to the given NullableString and assigns it to the HexCode field.
func (o *ShopListingWithAssociationsImagesInner) SetHexCode(v string) {
	o.HexCode.Set(&v)
}
// SetHexCodeNil sets the value for HexCode to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetHexCodeNil() {
	o.HexCode.Set(nil)
}

// UnsetHexCode ensures that no value is present for HexCode, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetHexCode() {
	o.HexCode.Unset()
}

// GetRed returns the Red field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetRed() int32 {
	if o == nil || IsNil(o.Red.Get()) {
		var ret int32
		return ret
	}
	return *o.Red.Get()
}

// GetRedOk returns a tuple with the Red field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetRedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Red.Get(), o.Red.IsSet()
}

// HasRed returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasRed() bool {
	if o != nil && o.Red.IsSet() {
		return true
	}

	return false
}

// SetRed gets a reference to the given NullableInt32 and assigns it to the Red field.
func (o *ShopListingWithAssociationsImagesInner) SetRed(v int32) {
	o.Red.Set(&v)
}
// SetRedNil sets the value for Red to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetRedNil() {
	o.Red.Set(nil)
}

// UnsetRed ensures that no value is present for Red, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetRed() {
	o.Red.Unset()
}

// GetGreen returns the Green field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetGreen() int32 {
	if o == nil || IsNil(o.Green.Get()) {
		var ret int32
		return ret
	}
	return *o.Green.Get()
}

// GetGreenOk returns a tuple with the Green field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetGreenOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Green.Get(), o.Green.IsSet()
}

// HasGreen returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasGreen() bool {
	if o != nil && o.Green.IsSet() {
		return true
	}

	return false
}

// SetGreen gets a reference to the given NullableInt32 and assigns it to the Green field.
func (o *ShopListingWithAssociationsImagesInner) SetGreen(v int32) {
	o.Green.Set(&v)
}
// SetGreenNil sets the value for Green to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetGreenNil() {
	o.Green.Set(nil)
}

// UnsetGreen ensures that no value is present for Green, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetGreen() {
	o.Green.Unset()
}

// GetBlue returns the Blue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetBlue() int32 {
	if o == nil || IsNil(o.Blue.Get()) {
		var ret int32
		return ret
	}
	return *o.Blue.Get()
}

// GetBlueOk returns a tuple with the Blue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetBlueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Blue.Get(), o.Blue.IsSet()
}

// HasBlue returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasBlue() bool {
	if o != nil && o.Blue.IsSet() {
		return true
	}

	return false
}

// SetBlue gets a reference to the given NullableInt32 and assigns it to the Blue field.
func (o *ShopListingWithAssociationsImagesInner) SetBlue(v int32) {
	o.Blue.Set(&v)
}
// SetBlueNil sets the value for Blue to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetBlueNil() {
	o.Blue.Set(nil)
}

// UnsetBlue ensures that no value is present for Blue, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetBlue() {
	o.Blue.Unset()
}

// GetHue returns the Hue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetHue() int32 {
	if o == nil || IsNil(o.Hue.Get()) {
		var ret int32
		return ret
	}
	return *o.Hue.Get()
}

// GetHueOk returns a tuple with the Hue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetHueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hue.Get(), o.Hue.IsSet()
}

// HasHue returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasHue() bool {
	if o != nil && o.Hue.IsSet() {
		return true
	}

	return false
}

// SetHue gets a reference to the given NullableInt32 and assigns it to the Hue field.
func (o *ShopListingWithAssociationsImagesInner) SetHue(v int32) {
	o.Hue.Set(&v)
}
// SetHueNil sets the value for Hue to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetHueNil() {
	o.Hue.Set(nil)
}

// UnsetHue ensures that no value is present for Hue, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetHue() {
	o.Hue.Unset()
}

// GetSaturation returns the Saturation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetSaturation() int32 {
	if o == nil || IsNil(o.Saturation.Get()) {
		var ret int32
		return ret
	}
	return *o.Saturation.Get()
}

// GetSaturationOk returns a tuple with the Saturation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetSaturationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Saturation.Get(), o.Saturation.IsSet()
}

// HasSaturation returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasSaturation() bool {
	if o != nil && o.Saturation.IsSet() {
		return true
	}

	return false
}

// SetSaturation gets a reference to the given NullableInt32 and assigns it to the Saturation field.
func (o *ShopListingWithAssociationsImagesInner) SetSaturation(v int32) {
	o.Saturation.Set(&v)
}
// SetSaturationNil sets the value for Saturation to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetSaturationNil() {
	o.Saturation.Set(nil)
}

// UnsetSaturation ensures that no value is present for Saturation, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetSaturation() {
	o.Saturation.Unset()
}

// GetBrightness returns the Brightness field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetBrightness() int32 {
	if o == nil || IsNil(o.Brightness.Get()) {
		var ret int32
		return ret
	}
	return *o.Brightness.Get()
}

// GetBrightnessOk returns a tuple with the Brightness field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetBrightnessOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Brightness.Get(), o.Brightness.IsSet()
}

// HasBrightness returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasBrightness() bool {
	if o != nil && o.Brightness.IsSet() {
		return true
	}

	return false
}

// SetBrightness gets a reference to the given NullableInt32 and assigns it to the Brightness field.
func (o *ShopListingWithAssociationsImagesInner) SetBrightness(v int32) {
	o.Brightness.Set(&v)
}
// SetBrightnessNil sets the value for Brightness to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetBrightnessNil() {
	o.Brightness.Set(nil)
}

// UnsetBrightness ensures that no value is present for Brightness, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetBrightness() {
	o.Brightness.Unset()
}

// GetIsBlackAndWhite returns the IsBlackAndWhite field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetIsBlackAndWhite() bool {
	if o == nil || IsNil(o.IsBlackAndWhite.Get()) {
		var ret bool
		return ret
	}
	return *o.IsBlackAndWhite.Get()
}

// GetIsBlackAndWhiteOk returns a tuple with the IsBlackAndWhite field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetIsBlackAndWhiteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsBlackAndWhite.Get(), o.IsBlackAndWhite.IsSet()
}

// HasIsBlackAndWhite returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasIsBlackAndWhite() bool {
	if o != nil && o.IsBlackAndWhite.IsSet() {
		return true
	}

	return false
}

// SetIsBlackAndWhite gets a reference to the given NullableBool and assigns it to the IsBlackAndWhite field.
func (o *ShopListingWithAssociationsImagesInner) SetIsBlackAndWhite(v bool) {
	o.IsBlackAndWhite.Set(&v)
}
// SetIsBlackAndWhiteNil sets the value for IsBlackAndWhite to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetIsBlackAndWhiteNil() {
	o.IsBlackAndWhite.Set(nil)
}

// UnsetIsBlackAndWhite ensures that no value is present for IsBlackAndWhite, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetIsBlackAndWhite() {
	o.IsBlackAndWhite.Unset()
}

// GetCreationTsz returns the CreationTsz field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetCreationTsz() int32 {
	if o == nil || IsNil(o.CreationTsz) {
		var ret int32
		return ret
	}
	return *o.CreationTsz
}

// GetCreationTszOk returns a tuple with the CreationTsz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetCreationTszOk() (*int32, bool) {
	if o == nil || IsNil(o.CreationTsz) {
		return nil, false
	}
	return o.CreationTsz, true
}

// HasCreationTsz returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasCreationTsz() bool {
	if o != nil && !IsNil(o.CreationTsz) {
		return true
	}

	return false
}

// SetCreationTsz gets a reference to the given int32 and assigns it to the CreationTsz field.
func (o *ShopListingWithAssociationsImagesInner) SetCreationTsz(v int32) {
	o.CreationTsz = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetCreatedTimestamp() int32 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int32
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetCreatedTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int32 and assigns it to the CreatedTimestamp field.
func (o *ShopListingWithAssociationsImagesInner) SetCreatedTimestamp(v int32) {
	o.CreatedTimestamp = &v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetRank() int32 {
	if o == nil || IsNil(o.Rank) {
		var ret int32
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetRankOk() (*int32, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given int32 and assigns it to the Rank field.
func (o *ShopListingWithAssociationsImagesInner) SetRank(v int32) {
	o.Rank = &v
}

// GetUrl75x75 returns the Url75x75 field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetUrl75x75() string {
	if o == nil || IsNil(o.Url75x75) {
		var ret string
		return ret
	}
	return *o.Url75x75
}

// GetUrl75x75Ok returns a tuple with the Url75x75 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetUrl75x75Ok() (*string, bool) {
	if o == nil || IsNil(o.Url75x75) {
		return nil, false
	}
	return o.Url75x75, true
}

// HasUrl75x75 returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasUrl75x75() bool {
	if o != nil && !IsNil(o.Url75x75) {
		return true
	}

	return false
}

// SetUrl75x75 gets a reference to the given string and assigns it to the Url75x75 field.
func (o *ShopListingWithAssociationsImagesInner) SetUrl75x75(v string) {
	o.Url75x75 = &v
}

// GetUrl170x135 returns the Url170x135 field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetUrl170x135() string {
	if o == nil || IsNil(o.Url170x135) {
		var ret string
		return ret
	}
	return *o.Url170x135
}

// GetUrl170x135Ok returns a tuple with the Url170x135 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetUrl170x135Ok() (*string, bool) {
	if o == nil || IsNil(o.Url170x135) {
		return nil, false
	}
	return o.Url170x135, true
}

// HasUrl170x135 returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasUrl170x135() bool {
	if o != nil && !IsNil(o.Url170x135) {
		return true
	}

	return false
}

// SetUrl170x135 gets a reference to the given string and assigns it to the Url170x135 field.
func (o *ShopListingWithAssociationsImagesInner) SetUrl170x135(v string) {
	o.Url170x135 = &v
}

// GetUrl570xN returns the Url570xN field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetUrl570xN() string {
	if o == nil || IsNil(o.Url570xN) {
		var ret string
		return ret
	}
	return *o.Url570xN
}

// GetUrl570xNOk returns a tuple with the Url570xN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetUrl570xNOk() (*string, bool) {
	if o == nil || IsNil(o.Url570xN) {
		return nil, false
	}
	return o.Url570xN, true
}

// HasUrl570xN returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasUrl570xN() bool {
	if o != nil && !IsNil(o.Url570xN) {
		return true
	}

	return false
}

// SetUrl570xN gets a reference to the given string and assigns it to the Url570xN field.
func (o *ShopListingWithAssociationsImagesInner) SetUrl570xN(v string) {
	o.Url570xN = &v
}

// GetUrlFullxfull returns the UrlFullxfull field value if set, zero value otherwise.
func (o *ShopListingWithAssociationsImagesInner) GetUrlFullxfull() string {
	if o == nil || IsNil(o.UrlFullxfull) {
		var ret string
		return ret
	}
	return *o.UrlFullxfull
}

// GetUrlFullxfullOk returns a tuple with the UrlFullxfull field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShopListingWithAssociationsImagesInner) GetUrlFullxfullOk() (*string, bool) {
	if o == nil || IsNil(o.UrlFullxfull) {
		return nil, false
	}
	return o.UrlFullxfull, true
}

// HasUrlFullxfull returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasUrlFullxfull() bool {
	if o != nil && !IsNil(o.UrlFullxfull) {
		return true
	}

	return false
}

// SetUrlFullxfull gets a reference to the given string and assigns it to the UrlFullxfull field.
func (o *ShopListingWithAssociationsImagesInner) SetUrlFullxfull(v string) {
	o.UrlFullxfull = &v
}

// GetFullHeight returns the FullHeight field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetFullHeight() int32 {
	if o == nil || IsNil(o.FullHeight.Get()) {
		var ret int32
		return ret
	}
	return *o.FullHeight.Get()
}

// GetFullHeightOk returns a tuple with the FullHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetFullHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullHeight.Get(), o.FullHeight.IsSet()
}

// HasFullHeight returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasFullHeight() bool {
	if o != nil && o.FullHeight.IsSet() {
		return true
	}

	return false
}

// SetFullHeight gets a reference to the given NullableInt32 and assigns it to the FullHeight field.
func (o *ShopListingWithAssociationsImagesInner) SetFullHeight(v int32) {
	o.FullHeight.Set(&v)
}
// SetFullHeightNil sets the value for FullHeight to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetFullHeightNil() {
	o.FullHeight.Set(nil)
}

// UnsetFullHeight ensures that no value is present for FullHeight, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetFullHeight() {
	o.FullHeight.Unset()
}

// GetFullWidth returns the FullWidth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetFullWidth() int32 {
	if o == nil || IsNil(o.FullWidth.Get()) {
		var ret int32
		return ret
	}
	return *o.FullWidth.Get()
}

// GetFullWidthOk returns a tuple with the FullWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetFullWidthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullWidth.Get(), o.FullWidth.IsSet()
}

// HasFullWidth returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasFullWidth() bool {
	if o != nil && o.FullWidth.IsSet() {
		return true
	}

	return false
}

// SetFullWidth gets a reference to the given NullableInt32 and assigns it to the FullWidth field.
func (o *ShopListingWithAssociationsImagesInner) SetFullWidth(v int32) {
	o.FullWidth.Set(&v)
}
// SetFullWidthNil sets the value for FullWidth to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetFullWidthNil() {
	o.FullWidth.Set(nil)
}

// UnsetFullWidth ensures that no value is present for FullWidth, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetFullWidth() {
	o.FullWidth.Unset()
}

// GetAltText returns the AltText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShopListingWithAssociationsImagesInner) GetAltText() string {
	if o == nil || IsNil(o.AltText.Get()) {
		var ret string
		return ret
	}
	return *o.AltText.Get()
}

// GetAltTextOk returns a tuple with the AltText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShopListingWithAssociationsImagesInner) GetAltTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AltText.Get(), o.AltText.IsSet()
}

// HasAltText returns a boolean if a field has been set.
func (o *ShopListingWithAssociationsImagesInner) HasAltText() bool {
	if o != nil && o.AltText.IsSet() {
		return true
	}

	return false
}

// SetAltText gets a reference to the given NullableString and assigns it to the AltText field.
func (o *ShopListingWithAssociationsImagesInner) SetAltText(v string) {
	o.AltText.Set(&v)
}
// SetAltTextNil sets the value for AltText to be an explicit nil
func (o *ShopListingWithAssociationsImagesInner) SetAltTextNil() {
	o.AltText.Set(nil)
}

// UnsetAltText ensures that no value is present for AltText, not even an explicit nil
func (o *ShopListingWithAssociationsImagesInner) UnsetAltText() {
	o.AltText.Unset()
}

func (o ShopListingWithAssociationsImagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShopListingWithAssociationsImagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ListingId) {
		toSerialize["listing_id"] = o.ListingId
	}
	if !IsNil(o.ListingImageId) {
		toSerialize["listing_image_id"] = o.ListingImageId
	}
	if o.HexCode.IsSet() {
		toSerialize["hex_code"] = o.HexCode.Get()
	}
	if o.Red.IsSet() {
		toSerialize["red"] = o.Red.Get()
	}
	if o.Green.IsSet() {
		toSerialize["green"] = o.Green.Get()
	}
	if o.Blue.IsSet() {
		toSerialize["blue"] = o.Blue.Get()
	}
	if o.Hue.IsSet() {
		toSerialize["hue"] = o.Hue.Get()
	}
	if o.Saturation.IsSet() {
		toSerialize["saturation"] = o.Saturation.Get()
	}
	if o.Brightness.IsSet() {
		toSerialize["brightness"] = o.Brightness.Get()
	}
	if o.IsBlackAndWhite.IsSet() {
		toSerialize["is_black_and_white"] = o.IsBlackAndWhite.Get()
	}
	if !IsNil(o.CreationTsz) {
		toSerialize["creation_tsz"] = o.CreationTsz
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	if !IsNil(o.Url75x75) {
		toSerialize["url_75x75"] = o.Url75x75
	}
	if !IsNil(o.Url170x135) {
		toSerialize["url_170x135"] = o.Url170x135
	}
	if !IsNil(o.Url570xN) {
		toSerialize["url_570xN"] = o.Url570xN
	}
	if !IsNil(o.UrlFullxfull) {
		toSerialize["url_fullxfull"] = o.UrlFullxfull
	}
	if o.FullHeight.IsSet() {
		toSerialize["full_height"] = o.FullHeight.Get()
	}
	if o.FullWidth.IsSet() {
		toSerialize["full_width"] = o.FullWidth.Get()
	}
	if o.AltText.IsSet() {
		toSerialize["alt_text"] = o.AltText.Get()
	}
	return toSerialize, nil
}

type NullableShopListingWithAssociationsImagesInner struct {
	value *ShopListingWithAssociationsImagesInner
	isSet bool
}

func (v NullableShopListingWithAssociationsImagesInner) Get() *ShopListingWithAssociationsImagesInner {
	return v.value
}

func (v *NullableShopListingWithAssociationsImagesInner) Set(val *ShopListingWithAssociationsImagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableShopListingWithAssociationsImagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableShopListingWithAssociationsImagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShopListingWithAssociationsImagesInner(val *ShopListingWithAssociationsImagesInner) *NullableShopListingWithAssociationsImagesInner {
	return &NullableShopListingWithAssociationsImagesInner{value: val, isSet: true}
}

func (v NullableShopListingWithAssociationsImagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShopListingWithAssociationsImagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


