/*
Etsy Open API v3

<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2023 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

API version: 3.0.0
Contact: developers@etsy.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShippingCarrierInternationalClassesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShippingCarrierInternationalClassesInner{}

// ShippingCarrierInternationalClassesInner Set of international mail classes of this shipping carrier.
type ShippingCarrierInternationalClassesInner struct {
	// The unique identifier of this mail class.
	MailClassKey *string `json:"mail_class_key,omitempty"`
	// The name of this mail class.
	Name *string `json:"name,omitempty"`
}

// NewShippingCarrierInternationalClassesInner instantiates a new ShippingCarrierInternationalClassesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShippingCarrierInternationalClassesInner() *ShippingCarrierInternationalClassesInner {
	this := ShippingCarrierInternationalClassesInner{}
	return &this
}

// NewShippingCarrierInternationalClassesInnerWithDefaults instantiates a new ShippingCarrierInternationalClassesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShippingCarrierInternationalClassesInnerWithDefaults() *ShippingCarrierInternationalClassesInner {
	this := ShippingCarrierInternationalClassesInner{}
	return &this
}

// GetMailClassKey returns the MailClassKey field value if set, zero value otherwise.
func (o *ShippingCarrierInternationalClassesInner) GetMailClassKey() string {
	if o == nil || IsNil(o.MailClassKey) {
		var ret string
		return ret
	}
	return *o.MailClassKey
}

// GetMailClassKeyOk returns a tuple with the MailClassKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingCarrierInternationalClassesInner) GetMailClassKeyOk() (*string, bool) {
	if o == nil || IsNil(o.MailClassKey) {
		return nil, false
	}
	return o.MailClassKey, true
}

// HasMailClassKey returns a boolean if a field has been set.
func (o *ShippingCarrierInternationalClassesInner) HasMailClassKey() bool {
	if o != nil && !IsNil(o.MailClassKey) {
		return true
	}

	return false
}

// SetMailClassKey gets a reference to the given string and assigns it to the MailClassKey field.
func (o *ShippingCarrierInternationalClassesInner) SetMailClassKey(v string) {
	o.MailClassKey = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ShippingCarrierInternationalClassesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingCarrierInternationalClassesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ShippingCarrierInternationalClassesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ShippingCarrierInternationalClassesInner) SetName(v string) {
	o.Name = &v
}

func (o ShippingCarrierInternationalClassesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShippingCarrierInternationalClassesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MailClassKey) {
		toSerialize["mail_class_key"] = o.MailClassKey
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableShippingCarrierInternationalClassesInner struct {
	value *ShippingCarrierInternationalClassesInner
	isSet bool
}

func (v NullableShippingCarrierInternationalClassesInner) Get() *ShippingCarrierInternationalClassesInner {
	return v.value
}

func (v *NullableShippingCarrierInternationalClassesInner) Set(val *ShippingCarrierInternationalClassesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingCarrierInternationalClassesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingCarrierInternationalClassesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingCarrierInternationalClassesInner(val *ShippingCarrierInternationalClassesInner) *NullableShippingCarrierInternationalClassesInner {
	return &NullableShippingCarrierInternationalClassesInner{value: val, isSet: true}
}

func (v NullableShippingCarrierInternationalClassesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingCarrierInternationalClassesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


